### ISSUE TITLE
Load checkpoints of UCF-101

### ISSUE THREAD

**Issue by Baicheng42** [zhipeng-wei/Image-to-Video-I2V-attack#7]
Hi! Thanks for your great work!
I met some question when loading the checkpoint **"i3d_resnet50"** of ucf101 which you offer.  The error is shown below. 

I checked that my enviroment and the version of gluoncv is the same as yours. I'm not familiar with the network from gluoncv so I don't know how to fix it. 

Could you please provide me some advice? Thanks!!

`Traceback (most recent call last):
  File "reference_ucf101.py", line 146, in <module>
    model = load_model(model_name)
  File "reference_ucf101.py", line 118, in load_model
    model.load_state_dict(torch.load(ckpt_path)['state_dict'])
  File "/home/delong/.conda/envs/transfer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for I3D_ResNetV1:
        Unexpected key(s) in state_dict: "res_layers.1.1.nonlocal_block.theta.weight", "res_layers.1.1.nonlocal_block.theta.bias", "res_layers.1.1.nonlocal_block.phi.weight", "res_layers.1.1.nonlocal_block.phi.bias", "res_layers.1.1.nonlocal_block.g.weight", "res_layers.1.1.nonlocal_block.g.bias", "res_layers.1.1.nonlocal_block.W.weight", "res_layers.1.1.nonlocal_block.W.bias", "res_layers.1.1.nonlocal_block.bn.weight", "res_layers.1.1.nonlocal_block.bn.bias", "res_layers.1.1.nonlocal_block.bn.running_mean", "res_layers.1.1.nonlocal_block.bn.running_var", "res_layers.1.1.nonlocal_block.bn.num_batches_tracked", "res_layers.1.1.nonlocal_block.W_bn.0.weight", "res_layers.1.1.nonlocal_block.W_bn.0.bias", "res_layers.1.1.nonlocal_block.W_bn.1.weight", "res_layers.1.1.nonlocal_block.W_bn.1.bias", "res_layers.1.1.nonlocal_block.W_bn.1.running_mean", "res_layers.1.1.nonlocal_block.W_bn.1.running_var", "res_layers.1.1.nonlocal_block.W_bn.1.num_batches_tracked", "res_layers.1.3.nonlocal_block.theta.weight", "res_layers.1.3.nonlocal_block.theta.bias", "res_layers.1.3.nonlocal_block.phi.weight", "res_layers.1.3.nonlocal_block.phi.bias", "res_layers.1.3.nonlocal_block.g.weight", "res_layers.1.3.nonlocal_block.g.bias", "res_layers.1.3.nonlocal_block.W.weight", "res_layers.1.3.nonlocal_block.W.bias", "res_layers.1.3.nonlocal_block.bn.weight", "res_layers.1.3.nonlocal_block.bn.bias", "res_layers.1.3.nonlocal_block.bn.running_mean", "res_layers.1.3.nonlocal_block.bn.running_var", "res_layers.1.3.nonlocal_block.bn.num_batches_tracked", "res_layers.1.3.nonlocal_block.W_bn.0.weight", "res_layers.1.3.nonlocal_block.W_bn.0.bias", "res_layers.1.3.nonlocal_block.W_bn.1.weight", "res_layers.1.3.nonlocal_block.W_bn.1.bias", "res_layers.1.3.nonlocal_block.W_bn.1.running_mean", "res_layers.1.3.nonlocal_block.W_bn.1.running_var", "res_layers.1.3.nonlocal_block.W_bn.1.num_batches_tracked", "res_layers.2.1.nonlocal_block.theta.weight", "res_layers.2.1.nonlocal_block.theta.bias", "res_layers.2.1.nonlocal_block.phi.weight", "res_layers.2.1.nonlocal_block.phi.bias", "res_layers.2.1.nonlocal_block.g.weight", "res_layers.2.1.nonlocal_block.g.bias", "res_layers.2.1.nonlocal_block.W.weight", "res_layers.2.1.nonlocal_block.W.bias", "res_layers.2.1.nonlocal_block.bn.weight", "res_layers.2.1.nonlocal_block.bn.bias", "res_layers.2.1.nonlocal_block.bn.running_mean", "res_layers.2.1.nonlocal_block.bn.running_var", "res_layers.2.1.nonlocal_block.bn.num_batches_tracked", "res_layers.2.1.nonlocal_block.W_bn.0.weight", "res_layers.2.1.nonlocal_block.W_bn.0.bias", "res_layers.2.1.nonlocal_block.W_bn.1.weight", "res_layers.2.1.nonlocal_block.W_bn.1.bias", "res_layers.2.1.nonlocal_block.W_bn.1.running_mean", "res_layers.2.1.nonlocal_block.W_bn.1.running_var", "res_layers.2.1.nonlocal_block.W_bn.1.num_batches_tracked", "res_layers.2.3.nonlocal_block.theta.weight", "res_layers.2.3.nonlocal_block.theta.bias", "res_layers.2.3.nonlocal_block.phi.weight", "res_layers.2.3.nonlocal_block.phi.bias", "res_layers.2.3.nonlocal_block.g.weight", "res_layers.2.3.nonlocal_block.g.bias", "res_layers.2.3.nonlocal_block.W.weight", "res_layers.2.3.nonlocal_block.W.bias", "res_layers.2.3.nonlocal_block.bn.weight", "res_layers.2.3.nonlocal_block.bn.bias", "res_layers.2.3.nonlocal_block.bn.running_mean", "res_layers.2.3.nonlocal_block.bn.running_var", "res_layers.2.3.nonlocal_block.bn.num_batches_tracked", "res_layers.2.3.nonlocal_block.W_bn.0.weight", "res_layers.2.3.nonlocal_block.W_bn.0.bias", "res_layers.2.3.nonlocal_block.W_bn.1.weight", "res_layers.2.3.nonlocal_block.W_bn.1.bias", "res_layers.2.3.nonlocal_block.W_bn.1.running_mean", "res_layers.2.3.nonlocal_block.W_bn.1.running_var", "res_layers.2.3.nonlocal_block.W_bn.1.num_batches_tracked", "res_layers.2.5.nonlocal_block.theta.weight", "res_layers.2.5.nonlocal_block.theta.bias", "res_layers.2.5.nonlocal_block.phi.weight", "res_layers.2.5.nonlocal_block.phi.bias", "res_layers.2.5.nonlocal_block.g.weight", "res_layers.2.5.nonlocal_block.g.bias", "res_layers.2.5.nonlocal_block.W.weight", "res_layers.2.5.nonlocal_block.W.bias", "res_layers.2.5.nonlocal_block.bn.weight", "res_layers.2.5.nonlocal_block.bn.bias", "res_layers.2.5.nonlocal_block.bn.running_mean", "res_layers.2.5.nonlocal_block.bn.running_var", "res_layers.2.5.nonlocal_block.bn.num_batches_tracked", "res_layers.2.5.nonlocal_block.W_bn.0.weight", "res_layers.2.5.nonlocal_block.W_bn.0.bias", "res_layers.2.5.nonlocal_block.W_bn.1.weight", "res_layers.2.5.nonlocal_block.W_bn.1.bias", "res_layers.2.5.nonlocal_block.W_bn.1.running_mean", "res_layers.2.5.nonlocal_block.W_bn.1.running_var", "res_layers.2.5.nonlocal_block.W_bn.1.num_batches_tracked".
`

**Comment by Baicheng42** [comment]
Sorry, I'm stupid.

I prepared the wrong yaml of i3d_resnet50_v1_kinetics400 instead of i3d_**nl**_resnet50_v1_kinetics400

forget me.
